name: flutter_application_1 # Or your actual project name
description: "A Flutter drawing application project."
publish_to: 'none' # Keep this for private projects

version: 1.0.0+1 # Or your current version

environment:
  # Use a recent Dart SDK constraint compatible with modern Flutter versions
  sdk: '>=3.4.0 <4.0.0' # Example: Requires Dart 3.4 or higher

dependencies:
  flutter:
    sdk: flutter

  # --- Core State & UI ---
  provider: ^6.1.2 # Latest stable version (check pub.dev)
  flutter_colorpicker: ^1.1.0 # Latest stable version

  # --- Calendar & Formatting ---
  table_calendar: ^3.1.0 # For calendar UI
  intl: ^0.19.0 # For date formatting

  # --- Media ---
  image_picker: ^1.1.2 # Latest stable version
  video_player: ^2.8.7 # Latest stable version

  # --- Utilities ---
  vector_math: ^2.1.4 # Latest stable version (usually stable)
  collection: ^1.18.0 # Recommended for listEquals, firstWhereOrNull etc.
  path_provider: ^2.1.5 # For accessing device file system
  uuid: ^4.5.1 # For generating unique IDs

  # --- Icons ---
  cupertino_icons: ^1.0.8 # Latest stable version (usually stable)

  # --- Add back other dependencies if you were using them ---
  # perfect_freehand: ^2.1.1 # If you were using this for smoother freehand drawing

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Use a linter version compatible with your SDK constraint
  flutter_lints: ^4.0.0 # Latest stable version

flutter:
  uses-material-design: true

  # --- Assets (Uncomment and add yours if needed) ---
  # assets:
  #   - images/

  # --- Fonts (Uncomment and add yours if needed) ---
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFontFamily-Regular.ttf
  #       - asset: fonts/YourFontFamily-Bold.ttf
  #         weight: 700